[package]
name = "rsynth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jack = "0.11.4"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
num = "0.4.1"
rayon = "1.7.0"
